runtime: php
env: flex

#[START env]
env_variables:
    # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
    # values obtained when configuring your Cloud SQL instance.
    CLOUDSQL_USER: USER
    CLOUDSQL_PASSWORD: PASSWORD

    ## Uncomment this line to use MySQL.
    # CLOUDSQL_DSN: mysql:host=127.0.0.1;dbname=DATABASE;unix_socket=/cloudsql/CONNECTION_NAME

    ## Uncomment this line to use PostgreSQL.
    # CLOUDSQL_DSN: pgsql:dbname=DATABASE;host=/cloudsql/CONNECTION_NAME
#[END env]

#[START cloudsql_settings]
# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: "CONNECTION_NAME"
#[END cloudsql_settings]