runtime: php
env: flex

beta_settings:
  cloud_sql_instances: "YOUR_DB_CONNECTION"

runtime_config:
  document_root: wordpress
  operating_system: ubuntu22
  runtime_version: 8.3

build_env_variables:
  NGINX_SERVES_STATIC_FILES: true
