# This app.yaml is for deploying to instances of Cloud SQL running MySQL.
# See app-postgres.yaml for running Cloud SQL with PostgreSQL.

runtime: php72

# [START gae_cloudsql_mysql_env]
env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  CLOUDSQL_USER: USER
  CLOUDSQL_PASSWORD: PASSWORD
  CLOUDSQL_DSN: "mysql:dbname=DATABASE;unix_socket=/cloudsql/CONNECTION_NAME"
# [END gae_cloudsql_mysql_env]

