# [START app_yaml]
runtime: php72
instance_class: F2

env_variables:
    GOOGLE_BUCKET_NAME: ""
    # populate these to use the "mysql" or "postres" backends
    CLOUDSQL_CONNECTION_NAME: ""
    CLOUDSQL_USER: ""
    CLOUDSQL_PASSWORD: ""
    ## Uncomment to give your database a name other than "bookshelf"
    # CLOUDSQL_DATABASE_NAME: ""
# [END app_yaml]
