runtime: php
env: flex

runtime_config:
  document_root: .
  # [START trace_setup_php_enabling_stackdriver_integration]
  enable_stackdriver_integration: true
  # [END trace_setup_php_enabling_stackdriver_integration]
