runtime: php
env: flex

runtime_config:
  document_root: .

# [START gae_flex_sendgrid_yaml]
gae_flex_sendgrid_yaml:
  SENDGRID_APIKEY: your-sendgrid-api-key
  SENDGRID_SENDER: your-sendgrid-sender
# [END gae_flex_sendgrid_yaml]
