runtime: php
env: flex

runtime_config:
  document_root: .
  operating_system: ubuntu22
  runtime_version: 8.3

# [START gae_flex_storage_yaml]
env_variables:
  GOOGLE_STORAGE_BUCKET: "your-bucket-name"
# [END gae_flex_storage_yaml]
