name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  php_cs_fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Run Script
      run: testing/run_cs_check.sh

  php_code_sniffer:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Dependencies
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: composer global require squizlabs/php_codesniffer
    - name: Run PHPCS Code Style Checker
      run: ~/.composer/vendor/bin/phpcs --standard=phpcs-ruleset.xml -p -s

  phpstan_static_analysis:
    name: PHPStan Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Get changed files
      id: changedFiles
      uses: tj-actions/changed-files@v44
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        state: open
    - name: Run Script
      run: |
        composer install -d testing/
        git fetch --no-tags --prune --depth=5 origin main
        bash testing/run_staticanalysis_check.sh
      env:
        FILES_CHANGED: ${{ steps.changedFiles.outputs.all_changed_files }}
        PULL_REQUEST_NUMBER: ${{ steps.findPr.outputs.pr }}
