name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  styles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Run Script
      run: testing/run_cs_check.sh

  staticanalysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 5
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        state: open
    - name: Run Script
      run: |
        composer install -d testing/
        git fetch --no-tags --prune --depth=5 origin main
        bash testing/run_staticanalysis_check.sh
      env:
        PULL_REQUEST_NUMBER: ${{ steps.findPr.outputs.pr }}

